name: kesademo
namespace: bf-kesademo
defaultLanguage: fi
nluThreshold: 0.75
timezoneOffset: 0
allowContextualQuestions: false
instance:
  name: Default Instance
  host: 'http://rasa:5005'
  projectId: NA23mMthqSpdyd6mc
