version: '3.3'
services:

  mongo:
    image: 'mongo:5.0.6'
    container_name: botfront-mongo
    restart: always
    networks:
      - botfront-network
    volumes:
      - './botfront-db:/data/db'
    ports:
      - '27017:27017'

  botfront:
    image: ghcr.io/auroraai-bot-platform/botfront:latest
    restart: always
    networks:
      - botfront-network
    ports:
      - 3000:3000
    environment:
      MONGO_URL: mongodb://mongo:27017/bf
      ROOT_URL: http://botfront:3000
      PORT: 3000
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    depends_on:
      - mongo

  rasa:
    image: ghcr.io/auroraai-bot-platform/rasa:latest
    networks:
      - botfront-network
    restart: always
    ports:
      - '5005:5005'
    volumes:
      - './models/:/app/models'
    environment:
      - BOTFRONT_ENV=development
      - BF_PROJECT_ID=AMCZErq42txFQ8Bt4
      - BF_URL=http://botfront:3000/graphql

  rasa-prod:
    image: ghcr.io/auroraai-bot-platform/rasa:latest
    networks:
      - botfront-network
    restart: always
    ports:
      - '5006:5005'
    volumes:
      - './models-prod/:/app/models'
    environment:
      - BOTFRONT_ENV=production
      - BF_PROJECT_ID=AMCZErq42txFQ8Bt4
      - BF_URL=http://botfront:3000/graphql

networks:
  botfront-network: {}
volumes:
  botfront-db: null
