class CodeFilter:
    def __init__(self, codes: dict, slot_name: str, default_value: str, parameter_based_on: str = None):
        self.codes = codes
        self.slot = slot_name
        self.default_value = default_value
        self.parameter_based_on = parameter_based_on

    def validate_selection(self, selection):
        if isinstance(selection, list):
            checked_selection = self.check_codes(selection)
        elif isinstance(selection, str):
            checked_selection = self.check_codes([selection])
        else:
            return None

        if checked_selection:
            if self.parameter_based_on == 'value':
                value_based_selection = self.code_to_value(checked_selection)
                return value_based_selection
            else:
                return checked_selection
        else:
            return None

    def check_codes(self, selection: list):
        ''' Go through codes selected and check if they exists in the codes dictionary. '''
        for code in selection:
            if code in self.codes.keys():
                continue
            else:
                selection.remove(code)
        return selection

    def code_to_value(self, selection: list):
        ''' If api parameter is based on code values instead of code key,
        we must select parameter value accordingly. '''
        selection_values = []

        for code in selection:
            try:
                value = self.codes[code]
                selection_values.append(value)
            except KeyError:
                continue

        return selection_values


REGION_CODES = {
    "01": "Uusimaa",
    "02": "Varsinais-Suomi",
    "04": "Satakunta",
    "05": "Kanta-Häme",
    "06": "Pirkanmaa",
    "07": "Päijät-Häme",
    "08": "Kymenlaakso",
    "09": "Etelä-Karjala",
    "10": "Etelä-Savo",
    "11": "Pohjois-Savo",
    "12": "Pohjois-Karjala",
    "13": "Keski-Suomi",
    "14": "Etelä-Pohjanmaa",
    "15": "Pohjanmaa",
    "16": "Keski-Pohjanmaa",
    "17": "Pohjois-Pohjanmaa",
    "18": "Kainuu",
    "19": "Lappi",
    "21": "Ahvenanmaa"
}

MUNICIPALITY_CODES = {
    "005": "Alajärvi",
    "009": "Alavieska",
    "010": "Alavus",
    "016": "Asikkala",
    "018": "Askola",
    "019": "Aura",
    "020": "Akaa",
    "035": "Brändö",
    "043": "Eckerö",
    "046": "Enonkoski",
    "047": "Enontekiö",
    "049": "Espoo",
    "050": "Eura",
    "051": "Eurajoki",
    "052": "Evijärvi",
    "060": "Finström",
    "061": "Forssa",
    "062": "Föglö",
    "065": "Geta",
    "069": "Haapajärvi",
    "071": "Haapavesi",
    "072": "Hailuoto",
    "074": "Halsua",
    "075": "Hamina",
    "076": "Hammarland",
    "077": "Hankasalmi",
    "078": "Hanko",
    "079": "Harjavalta",
    "081": "Hartola",
    "082": "Hattula",
    "086": "Hausjärvi",
    "090": "Heinävesi",
    "091": "Helsinki",
    "092": "Vantaa",
    "097": "Hirvensalmi",
    "098": "Hollola",
    "102": "Huittinen",
    "103": "Humppila",
    "105": "Hyrynsalmi",
    "106": "Hyvinkää",
    "108": "Hämeenkyrö",
    "109": "Hämeenlinna",
    "111": "Heinola",
    "139": "Ii",
    "140": "Iisalmi",
    "142": "Iitti",
    "143": "Ikaalinen",
    "145": "Ilmajoki",
    "146": "Ilomantsi",
    "148": "Inari",
    "149": "Inkoo",
    "151": "Isojoki",
    "152": "Isokyrö",
    "153": "Imatra",
    "165": "Janakkala",
    "167": "Joensuu",
    "169": "Jokioinen",
    "170": "Jomala",
    "171": "Joroinen",
    "172": "Joutsa",
    "176": "Juuka",
    "177": "Juupajoki",
    "178": "Juva",
    "179": "Jyväskylä",
    "181": "Jämijärvi",
    "182": "Jämsä",
    "186": "Järvenpää",
    "202": "Kaarina",
    "204": "Kaavi",
    "205": "Kajaani",
    "208": "Kalajoki",
    "211": "Kangasala",
    "213": "Kangasniemi",
    "214": "Kankaanpää",
    "216": "Kannonkoski",
    "217": "Kannus",
    "218": "Karijoki",
    "224": "Karkkila",
    "226": "Karstula",
    "230": "Karvia",
    "231": "Kaskinen",
    "232": "Kauhajoki",
    "233": "Kauhava",
    "235": "Kauniainen",
    "236": "Kaustinen",
    "239": "Keitele",
    "240": "Kemi",
    "241": "Keminmaa",
    "244": "Kempele",
    "245": "Kerava",
    "249": "Keuruu",
    "250": "Kihniö",
    "256": "Kinnula",
    "257": "Kirkkonummi",
    "260": "Kitee",
    "261": "Kittilä",
    "263": "Kiuruvesi",
    "265": "Kivijärvi",
    "271": "Kokemäki",
    "272": "Kokkola",
    "273": "Kolari",
    "275": "Konnevesi",
    "276": "Kontiolahti",
    "280": "Korsnäs",
    "284": "Koski Tl",
    "285": "Kotka",
    "286": "Kouvola",
    "287": "Kristiinankaupunki",
    "288": "Kruunupyy",
    "290": "Kuhmo",
    "291": "Kuhmoinen",
    "295": "Kumlinge",
    "297": "Kuopio",
    "300": "Kuortane",
    "301": "Kurikka",
    "304": "Kustavi",
    "305": "Kuusamo",
    "309": "Outokumpu",
    "312": "Kyyjärvi",
    "316": "Kärkölä",
    "317": "Kärsämäki",
    "318": "Kökar",
    "320": "Kemijärvi",
    "322": "Kemiönsaari",
    "398": "Lahti",
    "399": "Laihia",
    "400": "Laitila",
    "402": "Lapinlahti",
    "403": "Lappajärvi",
    "405": "Lappeenranta",
    "407": "Lapinjärvi",
    "408": "Lapua",
    "410": "Laukaa",
    "416": "Lemi",
    "417": "Lemland",
    "418": "Lempäälä",
    "420": "Leppävirta",
    "421": "Lestijärvi",
    "422": "Lieksa",
    "423": "Lieto",
    "425": "Liminka",
    "426": "Liperi",
    "430": "Loimaa",
    "433": "Loppi",
    "434": "Loviisa",
    "435": "Luhanka",
    "436": "Lumijoki",
    "438": "Lumparland",
    "440": "Luoto",
    "441": "Luumäki",
    "444": "Lohja",
    "445": "Parainen",
    "475": "Maalahti",
    "478": "Maarianhamina - Mariehamn",
    "480": "Marttila",
    "481": "Masku",
    "483": "Merijärvi",
    "484": "Merikarvia",
    "489": "Miehikkälä",
    "491": "Mikkeli",
    "494": "Muhos",
    "495": "Multia",
    "498": "Muonio",
    "499": "Mustasaari",
    "500": "Muurame",
    "503": "Mynämäki",
    "504": "Myrskylä",
    "505": "Mäntsälä",
    "507": "Mäntyharju",
    "508": "Mänttä-Vilppula",
    "529": "Naantali",
    "531": "Nakkila",
    "535": "Nivala",
    "536": "Nokia",
    "538": "Nousiainen",
    "541": "Nurmes",
    "543": "Nurmijärvi",
    "545": "Närpiö",
    "560": "Orimattila",
    "561": "Oripää",
    "562": "Orivesi",
    "563": "Oulainen",
    "564": "Oulu",
    "576": "Padasjoki",
    "577": "Paimio",
    "578": "Paltamo",
    "580": "Parikkala",
    "581": "Parkano",
    "583": "Pelkosenniemi",
    "584": "Perho",
    "588": "Pertunmaa",
    "592": "Petäjävesi",
    "593": "Pieksämäki",
    "595": "Pielavesi",
    "598": "Pietarsaari",
    "599": "Pedersören kunta",
    "601": "Pihtipudas",
    "604": "Pirkkala",
    "607": "Polvijärvi",
    "608": "Pomarkku",
    "609": "Pori",
    "611": "Pornainen",
    "614": "Posio",
    "615": "Pudasjärvi",
    "616": "Pukkila",
    "619": "Punkalaidun",
    "620": "Puolanka",
    "623": "Puumala",
    "624": "Pyhtää",
    "625": "Pyhäjoki",
    "626": "Pyhäjärvi",
    "630": "Pyhäntä",
    "631": "Pyhäranta",
    "635": "Pälkäne",
    "636": "Pöytyä",
    "638": "Porvoo",
    "678": "Raahe",
    "680": "Raisio",
    "681": "Rantasalmi",
    "683": "Ranua",
    "684": "Rauma",
    "686": "Rautalampi",
    "687": "Rautavaara",
    "689": "Rautjärvi",
    "691": "Reisjärvi",
    "694": "Riihimäki",
    "697": "Ristijärvi",
    "698": "Rovaniemi",
    "700": "Ruokolahti",
    "702": "Ruovesi",
    "704": "Rusko",
    "707": "Rääkkylä",
    "710": "Raasepori",
    "729": "Saarijärvi",
    "732": "Salla",
    "734": "Salo",
    "736": "Saltvik",
    "738": "Sauvo",
    "739": "Savitaipale",
    "740": "Savonlinna",
    "742": "Savukoski",
    "743": "Seinäjoki",
    "746": "Sievi",
    "747": "Siikainen",
    "748": "Siikajoki",
    "749": "Siilinjärvi",
    "751": "Simo",
    "753": "Sipoo",
    "755": "Siuntio",
    "758": "Sodankylä",
    "759": "Soini",
    "761": "Somero",
    "762": "Sonkajärvi",
    "765": "Sotkamo",
    "766": "Sottunga",
    "768": "Sulkava",
    "771": "Sund",
    "777": "Suomussalmi",
    "778": "Suonenjoki",
    "781": "Sysmä",
    "783": "Säkylä",
    "785": "Vaala",
    "790": "Sastamala",
    "791": "Siikalatva",
    "831": "Taipalsaari",
    "832": "Taivalkoski",
    "833": "Taivassalo",
    "834": "Tammela",
    "837": "Tampere",
    "844": "Tervo",
    "845": "Tervola",
    "846": "Teuva",
    "848": "Tohmajärvi",
    "849": "Toholampi",
    "850": "Toivakka",
    "851": "Tornio",
    "853": "Turku",
    "854": "Pello",
    "857": "Tuusniemi",
    "858": "Tuusula",
    "859": "Tyrnävä",
    "886": "Ulvila",
    "887": "Urjala",
    "889": "Utajärvi",
    "890": "Utsjoki",
    "892": "Uurainen",
    "893": "Uusikaarlepyy",
    "895": "Uusikaupunki",
    "905": "Vaasa",
    "908": "Valkeakoski",
    "915": "Varkaus",
    "918": "Vehmaa",
    "921": "Vesanto",
    "922": "Vesilahti",
    "924": "Veteli",
    "925": "Vieremä",
    "927": "Vihti",
    "931": "Viitasaari",
    "934": "Vimpeli",
    "935": "Virolahti",
    "936": "Virrat",
    "941": "Vårdö",
    "946": "Vöyri",
    "976": "Ylitornio",
    "977": "Ylivieska",
    "980": "Ylöjärvi",
    "981": "Ypäjä",
    "989": "Ähtäri",
    "992": "Äänekoski"
}

HOSPITAL_DISTRICT_CODES = {
    "00": "Ahvenanmaa",
    "03": "Varsinais-Suomen SHP",
    "04": "Satakunnan SHP",
    "05": "Kanta-Hämeen SHP",
    "06": "Pirkanmaan SHP",
    "07": "Päijät-Hämeen SHP",
    "08": "Kymenlaakson SHP",
    "09": "Etelä-Karjalan SHP",
    "10": "Etelä-Savon SHP",
    "11": "Itä-Savon SHP",
    "12": "Pohjois-Karjalan SHP",
    "13": "Pohjois-Savon SHP",
    "14": "Keski-Suomen SHP",
    "15": "Etelä-Pohjanmaan SHP",
    "16": "Vaasan SHP",
    "17": "Keski-Pohjanmaan SHP",
    "18": "Pohjois-Pohjanmaan SHP",
    "19": "Kainuun SHP",
    "20": "Länsi-Pohjan SHP",
    "21": "Lapin SHP",
    "25": "Helsingin ja Uudenmaan SHP"
}

SERVICE_CLASS_CODES = {
    "P1": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P1",
    "P1.1": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P1.1",
    "P1.2": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P1.2",
    "P1.3": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P1.3",
    "P1.4": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P1.4",
    "P1.5": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P1.5",
    "P2": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P2",
    "P2.1": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P2.1",
    "P2.2": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P2.2",
    "P2.3": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P2.3",
    "P2.4": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P2.4",
    "P2.5": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P2.5",
    "P3": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P3",
    "P3.1": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P3.1",
    "P3.2": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P3.2",
    "P3.3": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P3.3",
    "P3.4": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P3.4",
    "P3.5": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P3.5",
    "P3.6": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P3.6",
    "P3.7": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P3.7",
    "P3.8": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P3.8",
    "P3.9": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P3.9",
    "P4": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P4",
    "P4.1": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P4.1",
    "P4.2": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P4.2",
    "P4.3": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P4.3",
    "P4.4": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P4.4",
    "P4.5": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P4.5",
    "P4.6": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P4.6",
    "P4.7": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P4.7",
    "P4.8": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P4.8",
    "P4.9": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P4.9",
    "P4.10": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P4.10",
    "P4.11": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P4.11",
    "P4.12": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P4.12",
    "P4.13": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P4.13",
    "P4.14": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P4.14",
    "P5": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P5",
    "P5.1": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P5.1",
    "P5.2": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P5.2",
    "P5.3": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P5.3",
    "P5.4": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P5.4",
    "P5.5": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P5.5",
    "P5.6": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P5.6",
    "P5.7": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P5.7",
    "P5.8": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P5.8",
    "P5.9": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P5.9",
    "P5.10": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P5.10",
    "P5.11": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P5.11",
    "P5.12": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P5.12",
    "P5.13": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P5.13",
    "P5.14": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P5.14",
    "P5.15": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P5.15",
    "P5.16": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P5.16",
    "P5.17": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P5.17",
    "P5.18": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P5.18",
    "P5.19": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P5.19",
    "P5.20": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P5.20",
    "P5.21": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P5.21",
    "P6": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P6",
    "P6.1": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P6.1",
    "P6.2": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P6.2",
    "P6.3": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P6.3",
    "P6.4": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P6.4",
    "P6.5": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P6.5",
    "P6.6": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P6.6",
    "P6.7": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P6.7",
    "P6.8": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P6.8",
    "P6.9": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P6.9",
    "P6.10": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P6.10",
    "P6.11": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P6.11",
    "P6.12": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P6.12",
    "P6.13": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P6.13",
    "P6.14": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P6.14",
    "P6.15": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P6.15",
    "P7": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P7",
    "P7.1": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P7.1",
    "P7.2": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P7.2",
    "P7.3": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P7.3",
    "P7.4": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P7.4",
    "P7.5": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P7.5",
    "P7.6": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P7.6",
    "P7.7": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P7.7",
    "P7.8": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P7.8",
    "P7.9": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P7.9",
    "P7.10": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P7.10",
    "P7.11": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P7.11",
    "P7.12": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P7.12",
    "P8": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P8",
    "P8.1": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P8.1",
    "P8.2": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P8.2",
    "P8.3": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P8.3",
    "P8.4": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P8.4",
    "P9": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P9",
    "P10": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P10",
    "P10.1": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P10.1",
    "P10.2": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P10.2",
    "P10.3": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P10.3",
    "P10.4": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P10.4",
    "P10.5": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P10.5",
    "P10.6": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P10.6",
    "P10.7": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P10.7",
    "P10.8": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P10.8",
    "P11": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P11",
    "P11.1": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P11.1",
    "P11.2": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P11.2",
    "P11.3": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P11.3",
    "P11.4": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P11.4",
    "P11.5": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P11.5",
    "P11.6": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P11.6",
    "P11.7": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P11.7",
    "P11.8": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P11.8",
    "P11.9": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P11.9",
    "P12": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P12",
    "P12.1": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P12.1",
    "P12.2": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P12.2",
    "P12.3": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P12.3",
    "P12.4": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P12.4",
    "P13": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P13",
    "P13.1": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P13.1",
    "P13.2": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P13.2",
    "P13.3": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P13.3",
    "P13.4": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P13.4",
    "P13.5": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P13.5",
    "P14": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P14",
    "P14.1": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P14.1",
    "P14.2": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P14.2",
    "P14.3": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P14.3",
    "P14.4": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P14.4",
    "P14.5": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P14.5",
    "P15": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P15",
    "P15.1": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P15.1",
    "P15.2": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P15.2",
    "P15.3": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P15.3",
    "P15.4": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P15.4",
    "P15.5": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P15.5",
    "P15.6": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P15.6",
    "P15.7": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P15.7",
    "P15.8": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P15.8",
    "P15.9": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P15.9",
    "P16": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P16",
    "P16.1": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P16.1",
    "P16.2": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P16.2",
    "P16.3": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P16.3",
    "P16.4": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P16.4",
    "P16.5": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P16.5",
    "P16.6": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P16.6",
    "P16.7": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P16.7",
    "P16.8": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P16.8",
    "P16.9": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P16.9",
    "P17": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P17",
    "P17.1": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P17.1",
    "P17.2": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P17.2",
    "P17.3": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P17.3",
    "P18": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P18",
    "P18.1": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P18.1",
    "P18.2": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P18.2",
    "P19": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P19",
    "P19.1": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P19.1",
    "P19.2": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P19.2",
    "P19.3": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P19.3",
    "P19.4": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P19.4",
    "P19.5": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P19.5",
    "P19.6": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P19.6",
    "P20": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P20",
    "P20.1": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P20.1",
    "P20.2": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P20.2",
    "P20.3": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P20.3",
    "P21": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P21",
    "P21.1": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P21.1",
    "P21.2": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P21.2",
    "P22": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P22",
    "P22.1": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P22.1",
    "P22.2": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P22.2",
    "P22.3": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P22.3",
    "P22.4": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P22.4",
    "P22.5": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P22.5",
    "P22.6": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P22.6",
    "P22.7": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P22.7",
    "P22.8": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P22.8",
    "P22.9": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P22.9",
    "P23": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P23",
    "P23.1": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P23.1",
    "P23.2": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P23.2",
    "P23.3": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P23.3",
    "P23.5": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P23.5",
    "P23.6": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P23.6",
    "P23.7": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P23.7",
    "P24": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P24",
    "P24.1": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P24.1",
    "P24.2": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P24.2",
    "P24.3": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P24.3",
    "P24.4": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P24.4",
    "P24.5": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P24.5",
    "P24.6": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P24.6",
    "P25": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P25",
    "P25.1": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P25.1",
    "P25.2": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P25.2",
    "P25.3": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P25.3",
    "P25.4": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P25.4",
    "P25.5": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P25.5",
    "P25.6": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P25.6",
    "P25.7": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P25.7",
    "P26": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P26",
    "P26.1": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P26.1",
    "P26.2": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P26.2",
    "P26.3": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P26.3",
    "P27": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P27",
    "P27.1": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P27.1",
    "P27.2": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P27.2",
    "P27.3": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P27.3",
    "P27.4": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P27.4",
    "P27.5": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P27.5",
    "P23.4": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P23.4",
    "P9.1": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P9.1",
    "P9.2": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P9.2",
    "P9.3": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P9.3",
    "P9.4": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P9.4",
    "P9.5": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P9.5",
    "P9.6": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P9.6",
    "P28": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P28",
    "P28.1": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P28.1",
    "P28.2": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P28.2",
    "P28.3": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P28.3",
    "P28.4": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P28.4",
    "P28.5": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P28.5",
    "P28.6": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P28.6",
    "P28.7": "http://uri.suomi.fi/codelist/ptv/ptvserclass2/code/P28.7"
}