pipeline:
  - name: WhitespaceTokenizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 3
    max_ngram: 5
  - name: LanguageModelFeaturizer
    model_name: bert
    model_weights: rasa/LaBSE
    cache_dir: /app/models/bert
  - name: DIETClassifier
    epochs: 200
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    retrieval_intent: faq
  - name: ResponseSelector
    epochs: 100
    retrieval_intent: chitchat
language: fi


policies:
  - name: TEDPolicy
    epochs: 50
    max_history: 5
    batch_size:
      - 32
      - 64
  - name: RulePolicy
  - name: AugmentedMemoizationPolicy
