name: testbot
namespace: bf-testing
defaultLanguage: fi
nluThreshold: 0.75
timezoneOffset: 0
allowContextualQuestions: false
instance:
  name: Default Instance
  host: 'http://rasa:5005'
  projectId: XwaRnQmEeToto6qBr
