name: kielimallitesti
namespace: bf-kielimallitesti
defaultLanguage: fi
nluThreshold: 0.75
timezoneOffset: 0
allowContextualQuestions: false
instance:
  name: Default Instance
  host: 'http://rasa:5005'
  projectId: MuY92nnHsjdmjF8ci
