name: run-tests
on:
  pull_request:
    branches:
      - main

jobs:
  cloud-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: infra/aws
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js 14.x 
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install packages
        run: npm ci
      - name: Run tests
        run: npm run test
